//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports.Inventory {
    
    public partial class ItemCartReport : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "Reports.Inventory.ItemCartReport.repx");

            // Controls
            this.topMarginBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("topMarginBand1");
            this.detailBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("detailBand1");
            this.bottomMarginBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("bottomMarginBand1");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.table1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table1");
            this.tableRow1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow1");
            this.code = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("code");
            this.Item = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Item");
            this.tableCell3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell3");
            this.BranchNameCell = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("BranchNameCell");
            this.tableCell8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell8");
            this.tableCell4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell4");
            this.tableCell5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell5");
            this.tableCell12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell12");
            this.tableCell13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell13");
            this.tableCell24 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell24");
            this.tableCell25 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell25");
            this.tableCell27 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell27");
            this.tableCell29 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell29");
            this.table8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table8");
            this.table5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table5");
            this.table3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table3");
            this.table4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table4");
            this.line1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("line1");
            this.table7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table7");
            this.table6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table6");
            this.RptHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRSubreport>("RptHeader");
            this.RptHeader.ReportSource = new Reports.Headers.ReportHeaderAr_Landscape();
            this.tableRow8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow8");
            this.FromDateLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("FromDateLbl");
            this.tableCell10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell10");
            this.tableRow5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow5");
            this.ToDateLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("ToDateLbl");
            this.tableCell16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell16");
            this.tableRow3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow3");
            this.HeaderGroupName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("HeaderGroupName");
            this.tableCell6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell6");
            this.tableRow4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow4");
            this.HeaderItemName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("HeaderItemName");
            this.tableCell9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell9");
            this.tableRow7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow7");
            this.HeaderStoreName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("HeaderStoreName");
            this.tableCell28 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell28");
            this.tableRow6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow6");
            this.HeaderBranchName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("HeaderBranchName");
            this.tableCell26 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell26");
            this.table9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table9");
            this.tableRow9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow9");
            this.TotalLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("TotalLbl");
            this.tableCell7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell7");
            this.tableCell1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell1");
            this.tableCell14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell14");
            this.tableCell30 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell30");
            this.tableCell32 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell32");
            this.tableCell34 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell34");
            this.tableCell35 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell35");
            this.pageInfo2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo2");
            this.pageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo1");
            this.table10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table10");
            this.table2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table2");
            this.tableRow10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow10");
            this.tableCell11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell11");
            this.InQuntity = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("InQuntity");
            this.OutQuntity = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("OutQuntity");
            this.CurruntQuntity = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("CurruntQuntity");
            this.tableCell19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell19");
            this.tableRow2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow2");
            this.DocumentName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("DocumentName");
            this.DocCode = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("DocCode");
            this.DocDate = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("DocDate");
            this.QuntityIn = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("QuntityIn");
            this.UnitIn = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("UnitIn");
            this.QuntityOut = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("QuntityOut");
            this.UnitOut = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("UnitOut");
            this.QuntityCurrunt = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("QuntityCurrunt");
            this.UnitCurrunt = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("UnitCurrunt");
            this.PurchasePrice = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("PurchasePrice");
            this.AvgPurchasePrice = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("AvgPurchasePrice");
            this.DocumentValue = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("DocumentValue");
            this.BalanceValue = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("BalanceValue");

            // Parameters
            this.BranchFilter = reportInitializer.GetParameter("BranchFilter");
            this.StoreFilter = reportInitializer.GetParameter("StoreFilter");
            this.GroupFilter = reportInitializer.GetParameter("GroupFilter");
            this.ItemFilter = reportInitializer.GetParameter("ItemFilter");
            this.ToDateFilter = reportInitializer.GetParameter("ToDateFilter");
            this.FromDateFilter = reportInitializer.GetParameter("FromDateFilter");

            // Data Sources
            this.objectDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.ObjectBinding.ObjectDataSource>("objectDataSource1");

            // Styles
            this.Style1 = reportInitializer.GetStyle("Style1");
            this.Style2 = reportInitializer.GetStyle("Style2");
        }
        private DevExpress.XtraReports.UI.TopMarginBand topMarginBand1;
        private DevExpress.XtraReports.UI.DetailBand detailBand1;
        private DevExpress.XtraReports.UI.BottomMarginBand bottomMarginBand1;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.XRTable table1;
        private DevExpress.XtraReports.UI.XRTableRow tableRow1;
        private DevExpress.XtraReports.UI.XRTableCell code;
        private DevExpress.XtraReports.UI.XRTableCell Item;
        private DevExpress.XtraReports.UI.XRTableCell tableCell3;
        private DevExpress.XtraReports.UI.XRTableCell BranchNameCell;
        private DevExpress.XtraReports.UI.XRTableCell tableCell8;
        private DevExpress.XtraReports.UI.XRTableCell tableCell4;
        private DevExpress.XtraReports.UI.XRTableCell tableCell5;
        private DevExpress.XtraReports.UI.XRTableCell tableCell12;
        private DevExpress.XtraReports.UI.XRTableCell tableCell13;
        private DevExpress.XtraReports.UI.XRTableCell tableCell24;
        private DevExpress.XtraReports.UI.XRTableCell tableCell25;
        private DevExpress.XtraReports.UI.XRTableCell tableCell27;
        private DevExpress.XtraReports.UI.XRTableCell tableCell29;
        private DevExpress.XtraReports.UI.XRTable table8;
        private DevExpress.XtraReports.UI.XRTable table5;
        private DevExpress.XtraReports.UI.XRTable table3;
        private DevExpress.XtraReports.UI.XRTable table4;
        private DevExpress.XtraReports.UI.XRLine line1;
        private DevExpress.XtraReports.UI.XRTable table7;
        private DevExpress.XtraReports.UI.XRTable table6;
        private DevExpress.XtraReports.UI.XRSubreport RptHeader;
        private DevExpress.XtraReports.UI.XRTableRow tableRow8;
        private DevExpress.XtraReports.UI.XRTableCell FromDateLbl;
        private DevExpress.XtraReports.UI.XRTableCell tableCell10;
        private DevExpress.XtraReports.UI.XRTableRow tableRow5;
        private DevExpress.XtraReports.UI.XRTableCell ToDateLbl;
        private DevExpress.XtraReports.UI.XRTableCell tableCell16;
        private DevExpress.XtraReports.UI.XRTableRow tableRow3;
        private DevExpress.XtraReports.UI.XRTableCell HeaderGroupName;
        private DevExpress.XtraReports.UI.XRTableCell tableCell6;
        private DevExpress.XtraReports.UI.XRTableRow tableRow4;
        private DevExpress.XtraReports.UI.XRTableCell HeaderItemName;
        private DevExpress.XtraReports.UI.XRTableCell tableCell9;
        private DevExpress.XtraReports.UI.XRTableRow tableRow7;
        private DevExpress.XtraReports.UI.XRTableCell HeaderStoreName;
        private DevExpress.XtraReports.UI.XRTableCell tableCell28;
        private DevExpress.XtraReports.UI.XRTableRow tableRow6;
        private DevExpress.XtraReports.UI.XRTableCell HeaderBranchName;
        private DevExpress.XtraReports.UI.XRTableCell tableCell26;
        private DevExpress.XtraReports.UI.XRTable table9;
        private DevExpress.XtraReports.UI.XRTableRow tableRow9;
        private DevExpress.XtraReports.UI.XRTableCell TotalLbl;
        private DevExpress.XtraReports.UI.XRTableCell tableCell7;
        private DevExpress.XtraReports.UI.XRTableCell tableCell1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell14;
        private DevExpress.XtraReports.UI.XRTableCell tableCell30;
        private DevExpress.XtraReports.UI.XRTableCell tableCell32;
        private DevExpress.XtraReports.UI.XRTableCell tableCell34;
        private DevExpress.XtraReports.UI.XRTableCell tableCell35;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo2;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo1;
        private DevExpress.XtraReports.UI.XRTable table10;
        private DevExpress.XtraReports.UI.XRTable table2;
        private DevExpress.XtraReports.UI.XRTableRow tableRow10;
        private DevExpress.XtraReports.UI.XRTableCell tableCell11;
        private DevExpress.XtraReports.UI.XRTableCell InQuntity;
        private DevExpress.XtraReports.UI.XRTableCell OutQuntity;
        private DevExpress.XtraReports.UI.XRTableCell CurruntQuntity;
        private DevExpress.XtraReports.UI.XRTableCell tableCell19;
        private DevExpress.XtraReports.UI.XRTableRow tableRow2;
        private DevExpress.XtraReports.UI.XRTableCell DocumentName;
        private DevExpress.XtraReports.UI.XRTableCell DocCode;
        private DevExpress.XtraReports.UI.XRTableCell DocDate;
        private DevExpress.XtraReports.UI.XRTableCell QuntityIn;
        private DevExpress.XtraReports.UI.XRTableCell UnitIn;
        private DevExpress.XtraReports.UI.XRTableCell QuntityOut;
        private DevExpress.XtraReports.UI.XRTableCell UnitOut;
        private DevExpress.XtraReports.UI.XRTableCell QuntityCurrunt;
        private DevExpress.XtraReports.UI.XRTableCell UnitCurrunt;
        private DevExpress.XtraReports.UI.XRTableCell PurchasePrice;
        private DevExpress.XtraReports.UI.XRTableCell AvgPurchasePrice;
        private DevExpress.XtraReports.UI.XRTableCell DocumentValue;
        private DevExpress.XtraReports.UI.XRTableCell BalanceValue;
        private DevExpress.DataAccess.ObjectBinding.ObjectDataSource objectDataSource1;
        private DevExpress.XtraReports.UI.XRControlStyle Style1;
        private DevExpress.XtraReports.UI.XRControlStyle Style2;
        private DevExpress.XtraReports.Parameters.Parameter BranchFilter;
        private DevExpress.XtraReports.Parameters.Parameter StoreFilter;
        private DevExpress.XtraReports.Parameters.Parameter GroupFilter;
        private DevExpress.XtraReports.Parameters.Parameter ItemFilter;
        private DevExpress.XtraReports.Parameters.Parameter ToDateFilter;
        private DevExpress.XtraReports.Parameters.Parameter FromDateFilter;
    }
}
