//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports.Inventory {
    
    public partial class ItemSalesAnaysisReport : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "Reports.Inventory.ItemSalesAnaysisReport.repx");

            // Controls
            this.topMarginBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("topMarginBand1");
            this.detailBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("detailBand1");
            this.bottomMarginBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("bottomMarginBand1");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.table1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table1");
            this.tableRow1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow1");
            this.code = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("code");
            this.Item = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Item");
            this.tableCell3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell3");
            this.BranchNameCell = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("BranchNameCell");
            this.tableCell8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell8");
            this.tableCell4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell4");
            this.tableCell5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell5");
            this.tableCell12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell12");
            this.tableCell13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell13");
            this.table8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table8");
            this.table5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table5");
            this.table3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table3");
            this.table4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table4");
            this.line1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("line1");
            this.table7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table7");
            this.RptHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRSubreport>("RptHeader");
            this.RptHeader.ReportSource = new Reports.Headers.ReportHeaderAr_Landscape();
            this.tableRow8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow8");
            this.FromDateLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("FromDateLbl");
            this.tableCell10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell10");
            this.tableRow5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow5");
            this.ToDateLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("ToDateLbl");
            this.tableCell16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell16");
            this.tableRow3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow3");
            this.GroupFilterName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("GroupFilterName");
            this.tableCell6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell6");
            this.tableRow4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow4");
            this.ItemNameFilter = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("ItemNameFilter");
            this.tableCell9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell9");
            this.tableRow7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow7");
            this.CustomerNameFilter = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("CustomerNameFilter");
            this.tableCell28 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell28");
            this.table9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table9");
            this.tableRow9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow9");
            this.TotalLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("TotalLbl");
            this.tableCell7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell7");
            this.tableCell1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell1");
            this.tableCell14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell14");
            this.tableCell30 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell30");
            this.tableCell34 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell34");
            this.tableCell35 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell35");
            this.pageInfo2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo2");
            this.pageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo1");
            this.table2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table2");
            this.tableRow10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow10");
            this.tableRow2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow2");
            this.tableCell2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell2");
            this.SalesLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("SalesLbl");
            this.SalesReturnLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("SalesReturnLbl");
            this.SalesNetLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("SalesNetLbl");
            this.BranchNameLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("BranchNameLbl");
            this.CustomerName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("CustomerName");
            this.ItemName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("ItemName");
            this.QuntityIn = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("QuntityIn");
            this.ValueIn = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("ValueIn");
            this.QuntityReturn = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("QuntityReturn");
            this.ValueReturn = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("ValueReturn");
            this.QuntityNet = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("QuntityNet");
            this.ValueNet = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("ValueNet");

            // Parameters
            this.BranchFilter = reportInitializer.GetParameter("BranchFilter");
            this.GroupFilter = reportInitializer.GetParameter("GroupFilter");
            this.ItemFilter = reportInitializer.GetParameter("ItemFilter");
            this.ToDateFilter = reportInitializer.GetParameter("ToDateFilter");
            this.FromDateFilter = reportInitializer.GetParameter("FromDateFilter");
            this.CustomerFilter = reportInitializer.GetParameter("CustomerFilter");

            // Data Sources
            this.objectDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.ObjectBinding.ObjectDataSource>("objectDataSource1");

            // Styles
            this.Style1 = reportInitializer.GetStyle("Style1");
            this.Style2 = reportInitializer.GetStyle("Style2");
        }
        private DevExpress.XtraReports.UI.TopMarginBand topMarginBand1;
        private DevExpress.XtraReports.UI.DetailBand detailBand1;
        private DevExpress.XtraReports.UI.BottomMarginBand bottomMarginBand1;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.XRTable table1;
        private DevExpress.XtraReports.UI.XRTableRow tableRow1;
        private DevExpress.XtraReports.UI.XRTableCell code;
        private DevExpress.XtraReports.UI.XRTableCell Item;
        private DevExpress.XtraReports.UI.XRTableCell tableCell3;
        private DevExpress.XtraReports.UI.XRTableCell BranchNameCell;
        private DevExpress.XtraReports.UI.XRTableCell tableCell8;
        private DevExpress.XtraReports.UI.XRTableCell tableCell4;
        private DevExpress.XtraReports.UI.XRTableCell tableCell5;
        private DevExpress.XtraReports.UI.XRTableCell tableCell12;
        private DevExpress.XtraReports.UI.XRTableCell tableCell13;
        private DevExpress.XtraReports.UI.XRTable table8;
        private DevExpress.XtraReports.UI.XRTable table5;
        private DevExpress.XtraReports.UI.XRTable table3;
        private DevExpress.XtraReports.UI.XRTable table4;
        private DevExpress.XtraReports.UI.XRLine line1;
        private DevExpress.XtraReports.UI.XRTable table7;
        private DevExpress.XtraReports.UI.XRSubreport RptHeader;
        private DevExpress.XtraReports.UI.XRTableRow tableRow8;
        private DevExpress.XtraReports.UI.XRTableCell FromDateLbl;
        private DevExpress.XtraReports.UI.XRTableCell tableCell10;
        private DevExpress.XtraReports.UI.XRTableRow tableRow5;
        private DevExpress.XtraReports.UI.XRTableCell ToDateLbl;
        private DevExpress.XtraReports.UI.XRTableCell tableCell16;
        private DevExpress.XtraReports.UI.XRTableRow tableRow3;
        private DevExpress.XtraReports.UI.XRTableCell GroupFilterName;
        private DevExpress.XtraReports.UI.XRTableCell tableCell6;
        private DevExpress.XtraReports.UI.XRTableRow tableRow4;
        private DevExpress.XtraReports.UI.XRTableCell ItemNameFilter;
        private DevExpress.XtraReports.UI.XRTableCell tableCell9;
        private DevExpress.XtraReports.UI.XRTableRow tableRow7;
        private DevExpress.XtraReports.UI.XRTableCell CustomerNameFilter;
        private DevExpress.XtraReports.UI.XRTableCell tableCell28;
        private DevExpress.XtraReports.UI.XRTable table9;
        private DevExpress.XtraReports.UI.XRTableRow tableRow9;
        private DevExpress.XtraReports.UI.XRTableCell TotalLbl;
        private DevExpress.XtraReports.UI.XRTableCell tableCell7;
        private DevExpress.XtraReports.UI.XRTableCell tableCell1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell14;
        private DevExpress.XtraReports.UI.XRTableCell tableCell30;
        private DevExpress.XtraReports.UI.XRTableCell tableCell34;
        private DevExpress.XtraReports.UI.XRTableCell tableCell35;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo2;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo1;
        private DevExpress.XtraReports.UI.XRTable table2;
        private DevExpress.XtraReports.UI.XRTableRow tableRow10;
        private DevExpress.XtraReports.UI.XRTableRow tableRow2;
        private DevExpress.XtraReports.UI.XRTableCell tableCell2;
        private DevExpress.XtraReports.UI.XRTableCell SalesLbl;
        private DevExpress.XtraReports.UI.XRTableCell SalesReturnLbl;
        private DevExpress.XtraReports.UI.XRTableCell SalesNetLbl;
        private DevExpress.XtraReports.UI.XRTableCell BranchNameLbl;
        private DevExpress.XtraReports.UI.XRTableCell CustomerName;
        private DevExpress.XtraReports.UI.XRTableCell ItemName;
        private DevExpress.XtraReports.UI.XRTableCell QuntityIn;
        private DevExpress.XtraReports.UI.XRTableCell ValueIn;
        private DevExpress.XtraReports.UI.XRTableCell QuntityReturn;
        private DevExpress.XtraReports.UI.XRTableCell ValueReturn;
        private DevExpress.XtraReports.UI.XRTableCell QuntityNet;
        private DevExpress.XtraReports.UI.XRTableCell ValueNet;
        private DevExpress.DataAccess.ObjectBinding.ObjectDataSource objectDataSource1;
        private DevExpress.XtraReports.UI.XRControlStyle Style1;
        private DevExpress.XtraReports.UI.XRControlStyle Style2;
        private DevExpress.XtraReports.Parameters.Parameter BranchFilter;
        private DevExpress.XtraReports.Parameters.Parameter GroupFilter;
        private DevExpress.XtraReports.Parameters.Parameter ItemFilter;
        private DevExpress.XtraReports.Parameters.Parameter ToDateFilter;
        private DevExpress.XtraReports.Parameters.Parameter FromDateFilter;
        private DevExpress.XtraReports.Parameters.Parameter CustomerFilter;
    }
}
