<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<CopyRefAssembliesToPublishDirectory>false</CopyRefAssembliesToPublishDirectory>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Controllers\Sales\SalesInvoiceController.cs~RF300d35.TMP" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="EPPlus" Version="8.2.1" />
		<PackageReference Include="jquery" Version="3.7.1" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.Extensions" Version="6.0.36" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.ReportingServices.ReportViewerControl.WebForms" Version="150.1652.0" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.6" />
		<PackageReference Include="Rotativa.AspNetCore" Version="1.4.0" />
		<PackageReference Include="System.Drawing.Common" Version="8.0.10" />
		<PackageReference Include="System.Linq.Expressions" Version="4.3.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BusinessLayer\BusinessLayer.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="Views\EmployeeRenewalRequests1\ApproveSendRequestFinance.cshtml">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Content Update="Views\EmployeeRenewalRequests1\Create1.cshtml">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Content Update="Views\Role\Index.cshtml">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Content Update="Views\TrialBalance\Index3.cshtml">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Content Update="Views\TrialBalance\Index1.cshtml">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Reports\" />
		<Folder Include="wwwroot\Document\FormTemplate\" />
		<Folder Include="wwwroot\Document\Insurance\" />
		<Folder Include="wwwroot\Document\DrivingLicense\" />
		<Folder Include="wwwroot\Document\Customer\" />
		<Folder Include="wwwroot\Document\PaymentRecipt\" />
		<Folder Include="wwwroot\Images\ChangeOilImages\" />
		<Folder Include="wwwroot\Images\ChangeTireRequestImages\" />
		<Folder Include="wwwroot\Images\NewFolder\" />
		<Folder Include="wwwroot\Document\TuvInspection\" />
	</ItemGroup>

	<ItemGroup>
		<None Include="wwwroot\PriceOfferCreateEditJsFunctions.js" />
	</ItemGroup>

</Project>

