<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<!-- مهم: ده اللي يوفّر SignInManager/UserManager/RoleManager في Class Library -->
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<!-- !! اتشال Microsoft.AspNetCore.Identity.EntityFrameworkCore من هنا -->
		<PackageReference Include="Microsoft.Extensions.Localization" Version="8.0.10" />
		<PackageReference Include="System.Drawing.Common" Version="8.0.10" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DataAccessLayer\DataAccessLayer.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
		<PackageReference Include="Pkcs11Interop" Version="5.3.0" />
		<PackageReference Include="System.Security.Cryptography.Pkcs" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\SharedResources.ar.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\SharedResources.en.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
		</EmbeddedResource>
	</ItemGroup>

</Project>
