//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports.Financial {
    
    public partial class ReviewBalanceReport : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "Reports.Financial.ReviewBalanceReport.repx");

            // Controls
            this.topMarginBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("topMarginBand1");
            this.detailBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("detailBand1");
            this.bottomMarginBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("bottomMarginBand1");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.checkBox1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox1");
            this.table1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table1");
            this.tableRow1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow1");
            this.tableCell18 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell18");
            this.code = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("code");
            this.tableCell12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell12");
            this.Item = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Item");
            this.tableCell17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell17");
            this.tableCell4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell4");
            this.tableCell20 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell20");
            this.tableCell21 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell21");
            this.tableCell19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell19");
            this.tableCell5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell5");
            this.table8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table8");
            this.table5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table5");
            this.line1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("line1");
            this.table7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table7");
            this.RptHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRSubreport>("RptHeader");
            this.RptHeader.ReportSource = new Reports.Headers.ReportHeaderAr_Landscape();
            this.tableRow8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow8");
            this.FromDateLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("FromDateLbl");
            this.tableCell10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell10");
            this.tableRow5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow5");
            this.ToDateLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("ToDateLbl");
            this.tableCell16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell16");
            this.tableRow7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow7");
            this.AccountHedarFilter = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("AccountHedarFilter");
            this.tableCell28 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell28");
            this.table9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table9");
            this.tableRow9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow9");
            this.TotalLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("TotalLbl");
            this.tableCell13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell13");
            this.tableCell7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell7");
            this.tableCell1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell1");
            this.tableCell14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell14");
            this.tableCell9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell9");
            this.tableCell22 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell22");
            this.tableCell23 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell23");
            this.tableCell15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell15");
            this.pageInfo2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo2");
            this.pageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo1");
            this.table2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table2");
            this.tableRow10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow10");
            this.tableRow2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow2");
            this.detailsAccountLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("detailsAccountLbl");
            this.firstPeriodLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("firstPeriodLbl");
            this.beforeLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("beforeLbl");
            this.inPeriodLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("inPeriodLbl");
            this.balanceLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("balanceLbl");
            this.detailsAccountName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("detailsAccountName");
            this.detailsAccountCode = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("detailsAccountCode");
            this.firstPeriodDebitLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("firstPeriodDebitLbl");
            this.firstPeriodCreditLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("firstPeriodCreditLbl");
            this.beforeDebitLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("beforeDebitLbl");
            this.beforeCredit = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("beforeCredit");
            this.inDebit = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("inDebit");
            this.outCredit = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("outCredit");
            this.balanceDebitLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("balanceDebitLbl");
            this.balanceCreditLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("balanceCreditLbl");

            // Parameters
            this.AccountFilter = reportInitializer.GetParameter("AccountFilter");
            this.ToDateFilter = reportInitializer.GetParameter("ToDateFilter");
            this.FromDateFilter = reportInitializer.GetParameter("FromDateFilter");

            // Data Sources
            this.objectDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.ObjectBinding.ObjectDataSource>("objectDataSource1");

            // Styles
            this.Style1 = reportInitializer.GetStyle("Style1");
            this.Style2 = reportInitializer.GetStyle("Style2");
        }
        private DevExpress.XtraReports.UI.TopMarginBand topMarginBand1;
        private DevExpress.XtraReports.UI.DetailBand detailBand1;
        private DevExpress.XtraReports.UI.BottomMarginBand bottomMarginBand1;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox1;
        private DevExpress.XtraReports.UI.XRTable table1;
        private DevExpress.XtraReports.UI.XRTableRow tableRow1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell18;
        private DevExpress.XtraReports.UI.XRTableCell code;
        private DevExpress.XtraReports.UI.XRTableCell tableCell12;
        private DevExpress.XtraReports.UI.XRTableCell Item;
        private DevExpress.XtraReports.UI.XRTableCell tableCell17;
        private DevExpress.XtraReports.UI.XRTableCell tableCell4;
        private DevExpress.XtraReports.UI.XRTableCell tableCell20;
        private DevExpress.XtraReports.UI.XRTableCell tableCell21;
        private DevExpress.XtraReports.UI.XRTableCell tableCell19;
        private DevExpress.XtraReports.UI.XRTableCell tableCell5;
        private DevExpress.XtraReports.UI.XRTable table8;
        private DevExpress.XtraReports.UI.XRTable table5;
        private DevExpress.XtraReports.UI.XRLine line1;
        private DevExpress.XtraReports.UI.XRTable table7;
        private DevExpress.XtraReports.UI.XRSubreport RptHeader;
        private DevExpress.XtraReports.UI.XRTableRow tableRow8;
        private DevExpress.XtraReports.UI.XRTableCell FromDateLbl;
        private DevExpress.XtraReports.UI.XRTableCell tableCell10;
        private DevExpress.XtraReports.UI.XRTableRow tableRow5;
        private DevExpress.XtraReports.UI.XRTableCell ToDateLbl;
        private DevExpress.XtraReports.UI.XRTableCell tableCell16;
        private DevExpress.XtraReports.UI.XRTableRow tableRow7;
        private DevExpress.XtraReports.UI.XRTableCell AccountHedarFilter;
        private DevExpress.XtraReports.UI.XRTableCell tableCell28;
        private DevExpress.XtraReports.UI.XRTable table9;
        private DevExpress.XtraReports.UI.XRTableRow tableRow9;
        private DevExpress.XtraReports.UI.XRTableCell TotalLbl;
        private DevExpress.XtraReports.UI.XRTableCell tableCell13;
        private DevExpress.XtraReports.UI.XRTableCell tableCell7;
        private DevExpress.XtraReports.UI.XRTableCell tableCell1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell14;
        private DevExpress.XtraReports.UI.XRTableCell tableCell9;
        private DevExpress.XtraReports.UI.XRTableCell tableCell22;
        private DevExpress.XtraReports.UI.XRTableCell tableCell23;
        private DevExpress.XtraReports.UI.XRTableCell tableCell15;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo2;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo1;
        private DevExpress.XtraReports.UI.XRTable table2;
        private DevExpress.XtraReports.UI.XRTableRow tableRow10;
        private DevExpress.XtraReports.UI.XRTableRow tableRow2;
        private DevExpress.XtraReports.UI.XRTableCell detailsAccountLbl;
        private DevExpress.XtraReports.UI.XRTableCell firstPeriodLbl;
        private DevExpress.XtraReports.UI.XRTableCell beforeLbl;
        private DevExpress.XtraReports.UI.XRTableCell inPeriodLbl;
        private DevExpress.XtraReports.UI.XRTableCell balanceLbl;
        private DevExpress.XtraReports.UI.XRTableCell detailsAccountName;
        private DevExpress.XtraReports.UI.XRTableCell detailsAccountCode;
        private DevExpress.XtraReports.UI.XRTableCell firstPeriodDebitLbl;
        private DevExpress.XtraReports.UI.XRTableCell firstPeriodCreditLbl;
        private DevExpress.XtraReports.UI.XRTableCell beforeDebitLbl;
        private DevExpress.XtraReports.UI.XRTableCell beforeCredit;
        private DevExpress.XtraReports.UI.XRTableCell inDebit;
        private DevExpress.XtraReports.UI.XRTableCell outCredit;
        private DevExpress.XtraReports.UI.XRTableCell balanceDebitLbl;
        private DevExpress.XtraReports.UI.XRTableCell balanceCreditLbl;
        private DevExpress.DataAccess.ObjectBinding.ObjectDataSource objectDataSource1;
        private DevExpress.XtraReports.UI.XRControlStyle Style1;
        private DevExpress.XtraReports.UI.XRControlStyle Style2;
        private DevExpress.XtraReports.Parameters.Parameter AccountFilter;
        private DevExpress.XtraReports.Parameters.Parameter ToDateFilter;
        private DevExpress.XtraReports.Parameters.Parameter FromDateFilter;
    }
}
