//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports.Financial {
    
    public partial class TreasuryStatementOfAccountReport : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "Reports.Financial.TreasuryStatementOfAccountReport.repx");

            // Controls
            this.topMarginBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("topMarginBand1");
            this.detailBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("detailBand1");
            this.bottomMarginBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("bottomMarginBand1");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.table1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table1");
            this.tableRow1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow1");
            this.tableCell12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell12");
            this.code = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("code");
            this.Item = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Item");
            this.tableCell17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell17");
            this.tableCell4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell4");
            this.tableCell20 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell20");
            this.tableCell21 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell21");
            this.tableCell19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell19");
            this.tableCell5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell5");
            this.tableCell9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell9");
            this.table3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table3");
            this.table8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table8");
            this.table5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table5");
            this.line1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("line1");
            this.table7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table7");
            this.RptHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRSubreport>("RptHeader");
            this.RptHeader.ReportSource = new Reports.Headers.ReportHeaderAr_Landscape();
            this.tableRow3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow3");
            this.DocumentNameLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("DocumentNameLbl");
            this.tableCell3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell3");
            this.tableRow8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow8");
            this.FromDateLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("FromDateLbl");
            this.tableCell10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell10");
            this.tableRow5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow5");
            this.ToDateLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("ToDateLbl");
            this.tableCell16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell16");
            this.tableRow7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow7");
            this.TreasuryHedarFilter = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("TreasuryHedarFilter");
            this.tableCell28 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell28");
            this.table9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table9");
            this.tableRow9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow9");
            this.TotalLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("TotalLbl");
            this.tableCell13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell13");
            this.tableCell7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell7");
            this.tableCell1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell1");
            this.tableCell14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell14");
            this.tableCell15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell15");
            this.pageInfo2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo2");
            this.pageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo1");
            this.table2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table2");
            this.tableRow10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow10");
            this.tableRow2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow2");
            this.tableCell6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell6");
            this.TransactionsLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("TransactionsLbl");
            this.BalanceLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("BalanceLbl");
            this.tableCell8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell8");
            this.Serial = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Serial");
            this.detailsEntryNumber = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("detailsEntryNumber");
            this.detailsEntryDate = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("detailsEntryDate");
            this.detailsDocumentNumber = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("detailsDocumentNumber");
            this.detailsDocumentName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("detailsDocumentName");
            this.Debit = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Debit");
            this.Credit = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Credit");
            this.BalanceDebit = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("BalanceDebit");
            this.BalanceCredit = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("BalanceCredit");
            this.detailsNotes = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("detailsNotes");

            // Parameters
            this.TreasuryFilter = reportInitializer.GetParameter("TreasuryFilter");
            this.ToDateFilter = reportInitializer.GetParameter("ToDateFilter");
            this.FromDateFilter = reportInitializer.GetParameter("FromDateFilter");
            this.DocumentFilter = reportInitializer.GetParameter("DocumentFilter");

            // Data Sources
            this.objectDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.ObjectBinding.ObjectDataSource>("objectDataSource1");

            // Styles
            this.Style1 = reportInitializer.GetStyle("Style1");
            this.Style2 = reportInitializer.GetStyle("Style2");
        }
        private DevExpress.XtraReports.UI.TopMarginBand topMarginBand1;
        private DevExpress.XtraReports.UI.DetailBand detailBand1;
        private DevExpress.XtraReports.UI.BottomMarginBand bottomMarginBand1;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.XRTable table1;
        private DevExpress.XtraReports.UI.XRTableRow tableRow1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell12;
        private DevExpress.XtraReports.UI.XRTableCell code;
        private DevExpress.XtraReports.UI.XRTableCell Item;
        private DevExpress.XtraReports.UI.XRTableCell tableCell17;
        private DevExpress.XtraReports.UI.XRTableCell tableCell4;
        private DevExpress.XtraReports.UI.XRTableCell tableCell20;
        private DevExpress.XtraReports.UI.XRTableCell tableCell21;
        private DevExpress.XtraReports.UI.XRTableCell tableCell19;
        private DevExpress.XtraReports.UI.XRTableCell tableCell5;
        private DevExpress.XtraReports.UI.XRTableCell tableCell9;
        private DevExpress.XtraReports.UI.XRTable table3;
        private DevExpress.XtraReports.UI.XRTable table8;
        private DevExpress.XtraReports.UI.XRTable table5;
        private DevExpress.XtraReports.UI.XRLine line1;
        private DevExpress.XtraReports.UI.XRTable table7;
        private DevExpress.XtraReports.UI.XRSubreport RptHeader;
        private DevExpress.XtraReports.UI.XRTableRow tableRow3;
        private DevExpress.XtraReports.UI.XRTableCell DocumentNameLbl;
        private DevExpress.XtraReports.UI.XRTableCell tableCell3;
        private DevExpress.XtraReports.UI.XRTableRow tableRow8;
        private DevExpress.XtraReports.UI.XRTableCell FromDateLbl;
        private DevExpress.XtraReports.UI.XRTableCell tableCell10;
        private DevExpress.XtraReports.UI.XRTableRow tableRow5;
        private DevExpress.XtraReports.UI.XRTableCell ToDateLbl;
        private DevExpress.XtraReports.UI.XRTableCell tableCell16;
        private DevExpress.XtraReports.UI.XRTableRow tableRow7;
        private DevExpress.XtraReports.UI.XRTableCell TreasuryHedarFilter;
        private DevExpress.XtraReports.UI.XRTableCell tableCell28;
        private DevExpress.XtraReports.UI.XRTable table9;
        private DevExpress.XtraReports.UI.XRTableRow tableRow9;
        private DevExpress.XtraReports.UI.XRTableCell TotalLbl;
        private DevExpress.XtraReports.UI.XRTableCell tableCell13;
        private DevExpress.XtraReports.UI.XRTableCell tableCell7;
        private DevExpress.XtraReports.UI.XRTableCell tableCell1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell14;
        private DevExpress.XtraReports.UI.XRTableCell tableCell15;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo2;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo1;
        private DevExpress.XtraReports.UI.XRTable table2;
        private DevExpress.XtraReports.UI.XRTableRow tableRow10;
        private DevExpress.XtraReports.UI.XRTableRow tableRow2;
        private DevExpress.XtraReports.UI.XRTableCell tableCell6;
        private DevExpress.XtraReports.UI.XRTableCell TransactionsLbl;
        private DevExpress.XtraReports.UI.XRTableCell BalanceLbl;
        private DevExpress.XtraReports.UI.XRTableCell tableCell8;
        private DevExpress.XtraReports.UI.XRTableCell Serial;
        private DevExpress.XtraReports.UI.XRTableCell detailsEntryNumber;
        private DevExpress.XtraReports.UI.XRTableCell detailsEntryDate;
        private DevExpress.XtraReports.UI.XRTableCell detailsDocumentNumber;
        private DevExpress.XtraReports.UI.XRTableCell detailsDocumentName;
        private DevExpress.XtraReports.UI.XRTableCell Debit;
        private DevExpress.XtraReports.UI.XRTableCell Credit;
        private DevExpress.XtraReports.UI.XRTableCell BalanceDebit;
        private DevExpress.XtraReports.UI.XRTableCell BalanceCredit;
        private DevExpress.XtraReports.UI.XRTableCell detailsNotes;
        private DevExpress.DataAccess.ObjectBinding.ObjectDataSource objectDataSource1;
        private DevExpress.XtraReports.UI.XRControlStyle Style1;
        private DevExpress.XtraReports.UI.XRControlStyle Style2;
        private DevExpress.XtraReports.Parameters.Parameter TreasuryFilter;
        private DevExpress.XtraReports.Parameters.Parameter ToDateFilter;
        private DevExpress.XtraReports.Parameters.Parameter FromDateFilter;
        private DevExpress.XtraReports.Parameters.Parameter DocumentFilter;
    }
}
